### ISSUE TITLE
Sveltekit update dependency to 4.0.5 error

### ISSUE THREAD

**Issue by alextran1502** [willnguyen1312/zoom-image#170]
Hello Name,

Thank you for your library. I am updating my application to Svelte 4 and apparently run into an issue with the zoom-image. Can you help me with some pointers. 

Here is what I have in my project `package.json`

```json
"devDependencies": {
  "svelte": "^4.0.5",
[...]
}
"dependencies": {
  "@zoom-image/svelte": "^0.1.8",
[...]
}
```

Here is the error message

![image](https://github.com/willnguyen1312/zoom-image/assets/27055614/b2424353-a7fb-4da2-af2c-82b488548a63)

**Comment by willnguyen1312** [comment]
Hi, @alextran1502. Sorry for causing the inconvenience. I just patched the @zoom-image/svelte package. It should fix your current issue. Please let me know how it goes on your end, thanks :)

Demo - https://stackblitz.com/edit/willnguyen1312-zoom-image-v3uort?file=package.json

**Comment by alextran1502** [comment]
Thank you for your quick response. I confirmed that the issue has been fixed.
