### ISSUE TITLE
Zoom prevents scroll on desktop

### ISSUE THREAD

**Issue by arobbins** [willnguyen1312/zoom-image#224]
### Describe the bug

Let's say you're using this library to enable zoom in an ecommerce context.

On desktop, page scroll works as long as scroll is initiated outside of an image. (See first few seconds of linked video).

However as soon as the user begins zooming an image, a scroll lock is enabled. This provides a poor UX since the user expects to be able to always scroll through the page with a two finger gesture. Additionally, if they scroll through the page and their cursor lands on an image accidentally, frustration may ensue due to not being able to scroll up or down.

So the core issue is this: on desktop users are required to manually move their cursor outside of an image to continue scrolling down the page.

I'm using the `useZoomImageMove` React hook here.

I understand that this may be the expected behavior for some scenarios. However it would be nice to have the ability to disable scroll lock as well.

### Reproduction

https://www.loom.com/share/4fa5224b4fbe46928b906b0e2ea5c603?sid=7f25084e-455c-452d-982b-31a3fa40876f

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/willnguyen1312/zoom-image/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is available

**Comment by ChetSocio** [comment]
+1

**Comment by willnguyen1312** [comment]
Hi guys, I added `disableScrollLock` option to zoom images on move, please feel free to use it to tailor your specific use case ;)

https://willnguyen1312.github.io/zoom-image/api/createZoomImageMove.html#type-declaration

**Comment by willnguyen1312** [comment]
Hi @ChetSocio, please keep an eye on #232. Thanks 😉

**Comment by ChetSocio** [comment]
Thank you you had already fixed it😅😅 .  Do you have any idea on how to make it responsive. When I decreasebthe browser size there is unknown space and when i hover on product image, the zoom div had taken that whole space and leaves the overflow when i decrease browser width. You can already see it on the previous reproduced containers.

**Comment by willnguyen1312** [comment]
Hi @ChetSocio. It's up to the developers to handle that. As library won't be able to solve everyone's problems but rather focus on specific jobs. You definitely can use [media query](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_media_queries/Using_media_queries) for that purpose. That's how I did it for the doc site :)

P/s: Please open [a new dedicated issue](https://github.com/willnguyen1312/zoom-image/issues/new/choose) to discuss rather than comment on other issues like this in the future. Thanks so much :)
