### ISSUE TITLE
Allow to rotate the zoomed image

### ISSUE THREAD

**Issue by Stevie-Ray** [willnguyen1312/zoom-image#237]
### Description of the problem

Hi @willnguyen1312 

I'm building a Vue file viewer with scale / rotate functionality that uses `useZoomImageWheel`. But when combing rotate and scale functionality the scale (zoom) controls get inverted.

This can  easily be fixed by allowing to set an `zoomElement` next to a `imageContainer`. where `getSourceImage` looks for a `zoomElement` before the <img> tag.

With this option the zoom can be a container div while the inner image can be rotated and the zoom controls will work as intended.

**Comment by willnguyen1312** [comment]
Hi @Stevie-Ray, thanks for your input!

> I'm building a Vue file viewer with scale / rotate functionality that uses useZoomImageWheel. But when combining rotate and scale functionality the scale (zoom) controls get inverted.

Could you give me a minimal reproduction of this so I can understand clearly what you are trying to achieve?

> This can easily be fixed by allowing to set an zoomElement next to a imageContainer. where getSourceImage looks for a zoomElement before the  tag.

> With this option the zoom can be a container div while the inner image can be rotated and the zoom controls will work as intended.

Sorry, I don't understand this part. Please feel free to open PR to propose your approach as you seem to know the `getSourceImage` function already. I will learn something new from this ;)

I have done video and image zooming with rotation before at https://evidence.com in my previous job. Rotation can be tricky when in use with zooming as we needed to make sure it's fully visible within its container in both landscape and portrait mode (we only supported 90, 180 and 270 degrees rotation). Container and image aspect ratios are taken into consideration. I think I can help with this. I did that in React and didn't port to this library to keep it lightweight plus no one has asked for this feature yet 😝. I just want to make sure I can support your use case and others properly. Thanks 😊

**Comment by Stevie-Ray** [comment]
Hi @willnguyen1312 thanks for the quick reply,

So [here](https://stackblitz.com/edit/willnguyen1312-zoom-image-kstetv) i'll illustrate the problem.
When using the mouse/wheel the image moves in the wrong direction.

I would propose to be able to do something like: 

```
function createZoomImageWheel(
  container: HTMLElement,
  element?: HTMLElement,
  options?: ZoomImageWheelOptions,
)
```

The optional element can be used  to apply the zoom effect to a 'image wrapper' in the container.
This allows to rotate the inner image .

```
<div id="container">
  <div id="element" transform-origin: 0px 0px; transform: translate(0px, -500px) scale(2);>
    <img  src="image.webp" style="rotate: 90deg;">
  </div>
</div>
```
I think that should do the trick. Another option would be to build a rotate function that fixes the transform / translate but I guess that would require more work. My typescript knowledge is good enough to create a PR thats why i ask you for help :)

**Comment by willnguyen1312** [comment]
Hi @Stevie-Ray, thanks for illuminating your approach. I tried and learned something new indeed :) Unfortunately, it won't solve the issue completely. It seemed to work because the image I chose to use for the demo is having the perfect aspect ratio of 1:1. Rotation won't cause the image to be distorted. Yet, it will for other aspect ratios. Also, it will implicitly add an extra layer of DOM element, which will cause more or less confusion to the developers who consume this feature. As of now, it only uses one overflow hidden container and one scalable image. I think I am going to spend some time this week to port the feature I worked on mentioned above. It's been battle-tested for years and I believe it will solve your problems. Please stay tuned and don't hesitate to reach out if you have any concerns. Thanks :)

<img width="1066" alt="image" src="https://github.com/willnguyen1312/zoom-image/assets/17794897/db860a16-dcfd-4cc3-a45d-5b298082230e">

**Comment by willnguyen1312** [comment]
Hi @Stevie-Ray, I think I got something working. Could you please help me to give it a try and give me feedback? Thanks so much in advance :)

You can either clone the development branch linked to this issue and run `pnpm start-vue` or start straight from [here](https://stackblitz.com/edit/github-8t4ygk?file=examples%2Fwith-vue%2Fsrc%2FApp.vue) in StackBlitz 😊

Below is a little demo I put together, cheer! 🎉 

 

https://github.com/willnguyen1312/zoom-image/assets/17794897/f7eba1cb-c450-44b0-bf1b-0cfb94bda65d

**Comment by Stevie-Ray** [comment]
That's exactly what I'm looking for, thanks for picking it up so quickly! The `currentRotation` switch statement lgtm  🚀
