### ISSUE TITLE
Zoomed image border breaking screen on first render

### ISSUE THREAD

**Issue by raiffsaid** [willnguyen1312/zoom-image#273]
### Describe the bug

Hello @willnguyen1312! I have installed your library today and its pretty cool, but I am stucking with this issue that when I first render the image on the screen. I discovered that the zoomed image somehow appears on the side of the original one, but not totally, only its borders like the image below:

![Screenshot from 2024-03-25 16-34-22](https://github.com/willnguyen1312/zoom-image/assets/28994297/1ac72fb9-a633-402f-b5aa-ee393f293dcd)
(borders to the right side)

After I click to zoom the image, the screen returns to normal:

![Screenshot from 2024-03-25 16-35-34](https://github.com/willnguyen1312/zoom-image/assets/28994297/d3c18193-8531-4a48-9e84-f1c9f3bb0855)
(no borders)

### Reproduction

https://stackblitz.com/edit/stackblitz-starters-hb8af1?file=app%2Fpage.tsx

### Used Package Manager

yarn

### Validations

- [X] Check that there isn't [already an issue](https://github.com/willnguyen1312/zoom-image/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is available

**Comment by willnguyen1312** [comment]
Hi Raiff, I fixed an issue in the latest release. Please feel free to check it out and let me know if there is anything I could support form my end. Thanks so much :)

**Comment by raiffsaid** [comment]
Thanks @willnguyen1312! Everything is working like a charm
