### ISSUE TITLE
Zoom Image Angular Issues

### ISSUE THREAD

**Issue by janwidmer** [willnguyen1312/zoom-image#310]
### Describe the bug

I am trying to use your plugin in my Angular Application:
Angular: 17.3.9
Zoom Image Core: 0.36.2
Zoom Image Angular Adapter: 0.2.19

I looked at the example https://stackblitz.com/edit/willnguyen1312-zoom-image-x7vadc and tried to implement it like this.

First problem is when trying to run `npm i`:
<img width="599" alt="image" src="https://github.com/willnguyen1312/zoom-image/assets/3381820/69010956-ea68-4371-96ae-493afb04b112">

This is caused by a peer dependency to angular 16 in the angular package of the library.

As soon as I have the service `ZoomImageWheelService` in my constructor, I get the following error:
<img width="911" alt="image" src="https://github.com/willnguyen1312/zoom-image/assets/3381820/c8a26a4f-6480-428b-99d9-d429a30335a0">

Issue with Services seems to happen for all 4 Services.

### Reproduction

1. Checkout Repo
2. run `npm i`
3. Notice first Problem
4. run `npm i --force`
5. run `npm run start`
6. Open Browser
7. Notice second problem in browser dev tools

### Reproduction

https://github.com/janwidmer/zoom-image-angular-bug

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/willnguyen1312/zoom-image/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is available

**Comment by willnguyen1312** [comment]
Hi there, sorry for the late response as I'm on vacation now. Please try to use the latest version of Angular adapter `0.2.20`. Hope it works :)

**Comment by janwidmer** [comment]
@willnguyen1312 thanks for the quick fix. That fixes the first part of this issue occurring during `npm install`.

The second problem with the `no provider` error still occurs though.. any idea on that?

**Comment by willnguyen1312** [comment]
I think we need to add missing providers in Angular like [so](https://github.com/janwidmer/zoom-image-angular-bug/pull/1/files#diff-884f7f49640e5923f6bcac4c51d90340330a178f662defbe61e5f5aac1c512deR11). Hope it works on your end like mine too ;)

**Comment by janwidmer** [comment]
@willnguyen1312 aaah sorry my bad, I did not see the providers in the component. Now it works, thank you. :)
