### ISSUE TITLE
iOS and Safari show border around placeholder image

### ISSUE THREAD

**Issue by arobbins** [willnguyen1312/zoom-image#314]
### Describe the bug

Hey Nam! One of my users found another pesky bug for you.

On iOS and Safari, there is border (with alt text displaying) that shows above the images.

To see the bug, visit this page [https://muscleandspine.ca/shop/products/cork-massage-dual-ball/](https://muscleandspine.ca/shop/products/cork-massage-dual-ball/). Then click one of the thumbnail images _but don't trigger the image zoom._

<img width="1292" alt="Screenshot 2024-08-28 at 10 47 26 AM" src="https://github.com/user-attachments/assets/877122d7-a556-4107-9f33-00bf8e9e7a87">

On mobile, it's a bit more pronounced since the alt text shows up within the border as well.

I did some investigating and I believe it's because the `<img>` tag that the library adds to the DOM for the zoom is initially missing a `src` attribute. I don't think iOS and Safari like that :)

### Reproduction

https://muscleandspine.ca/shop/products/cork-massage-dual-ball/

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/willnguyen1312/zoom-image/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is available

**Comment by willnguyen1312** [comment]
Hi Andrew, I'm going to try to re-prod it later. Can you give me an example code if you have one already? That would be helpful 😄

**Comment by arobbins** [comment]
Awesome thanks Nam!

**Comment by willnguyen1312** [comment]
Hi Andrew. Can you update your dependency to use the latest version. I think it should work. From now on, zoom image will only be available on demand instead of sitting in the DOM forever 😄
