### ISSUE TITLE
Zoom prevents scroll on mobile

### ISSUE THREAD

**Issue by Maria-Lu** [willnguyen1312/zoom-image#321]
### Describe the bug

Hi 👋  I'm using the useZoomImageWheel Qwik hook.

On mobile, you can't scroll a page if you touch an image. And if you touch the image many times while trying to scroll the page, it gets zoomed. It becomes a real problem when the image is quite large and takes up the entire width and most of the height of the viewport because it makes it impossible to scroll the page at all.

### Reproduction

https://willnguyen1312.github.io/zoom-image/

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/willnguyen1312/zoom-image/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is available

**Comment by willnguyen1312** [comment]
Hi Maria, thanks for your feedback. I believe you can control when to activate zoom feature via `enabled` property which can be controlled on initialization and via setter function. Here is [the doc](https://willnguyen1312.github.io/zoom-image/api/createZoomImageWheel.html#createzoomimagewheel) for it. Hope it helps :)

**Comment by Maria-Lu** [comment]
Hi Nam, thanks for the quick reply :) Could you explain a bit further? I read the docs, but I haven't figured out how to solve my problem yet. Maybe I missed something obvious. I need zoom to be enabled and scroll to work at the same time so that if you use the pinch gesture on the image, it zooms, and if you try to scroll the page with your finger on the image, the page scrolls. But page scrolling works only as long as scroll is initiated outside the image. If your finger is on the image, you can’t scroll the page. Is there any way to fix this?

**Comment by willnguyen1312** [comment]
Oh. Thanks for explaining your use case, Maria. It's a bit different than what I have seen previously. After pinch, users actually can use their finger(s) to move zoomed image further. That's why we wanted to prevent zoom inside image in the first place. I will try to think of some API to help us achieve your use case next week. Enjoy the rest of your weekend, Maria :)

**Comment by willnguyen1312** [comment]
Hi Maria. I think I got something working for you. Can you please help me to check the behaviour of zoomed image working as per your expectation here - https://deploy-preview-322--zoom-image-library.netlify.app

I achieve the behaviour by providing an extra predicate to be called at runtime. You should be able to customize whether single touch action can trigger zoom via this option:

```tsx
shouldZoomOnSingleTouch: () => boolean
```

In the demo above, I use false as a boolean value to make it work 😊

**Comment by Maria-Lu** [comment]
Wow, that was fast! Is there a way to keep that behavior but also allow to move zoomed image around? I mean, let page scrolling work when you touch the image, but when the image is not zoomed. I’m sorry I haven’t explained this right before.

**Comment by willnguyen1312** [comment]
For sure, it can be controlled by you. You can check again in the link above. I achieve it by using this [one liner](https://github.com/willnguyen1312/zoom-image/pull/322/files#diff-637c57f02996e5e6c673f1323430bbf5d7054ad775466e7270d546d8ba27d4bbR118). You can turn it on if it's already zoomed, skip otherwise 😉

**Comment by Maria-Lu** [comment]
Awesome! That's exactly what I need, thanks a lot :)

**Comment by willnguyen1312** [comment]
Glad to hear, Maria. And, I just released it, please update your dependencies and try it out for your application 😊

**Comment by willnguyen1312** [comment]
Do you mind sharing with me the reproduction repo to look at? I tried in Qwik and it worked on my end 😃

**Comment by Maria-Lu** [comment]
I checked again, the problem was on my side. Everything is working) Thanks again!
