### ISSUE TITLE
Svelte 5

### ISSUE THREAD

**Issue by danieldietzler** [willnguyen1312/zoom-image#330]
### Describe the bug

`@zoom-image/svelte` currently has a peer dependency on `svelte ^3.0.0 || ^4.0.0`. It would be awesome if it'd also support svelte 5. :)

### Reproduction

N/A

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/willnguyen1312/zoom-image/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is available

**Comment by willnguyen1312** [comment]
Hi Daniel, sorry about the inconvenience. I'm going to update soon since Svelte 5 just released :)

**Comment by danieldietzler** [comment]
Hey, that's awesome! I really appreciate it :)

**Comment by danieldietzler** [comment]
Thank you so much for working on this and releasing it so quickly! :)

**Comment by willnguyen1312** [comment]
Sorry, the issue got closed automatically by Github. I re-opened it just in case anything missing. It's supporting Svelte 5 now - https://willnguyen1312.github.io/zoom-image/examples/svelte-5.html 😊 

It's my pleasure, Daniel. I really admire the work you guys have done wth immich app. Congratulation on [joining FUTO](https://immich.app/blog/2024/immich-core-team-goes-fulltime/). I really hope I could work on something mearniful like that one day - make the world a better via quality software ☺️

> Since the beginning of this adventure, my goal has always been to create a better world for my children. Memories are priceless, and privacy should not be a luxury.

Love it ❤️

**Comment by danieldietzler** [comment]
Thanks, it's looking good!
You're already working on something meaningful by contributing to open source software, that's awesome!
