### ISSUE TITLE
Zoom Image Hover Not Working When Swiftly Hovering

### ISSUE THREAD

**Issue by hfall** [willnguyen1312/zoom-image#49]
When you hover outside the image and then back swiftly, the zoom no longer works unless you repeat but slower. Not major but something to consider.

**Comment by willnguyen1312** [comment]
Hi @hfall, thanks so much for your feedback. Could you please give me the steps to reproduce the issue? I tried on my site and could not.

[Zoom Image Demo.webm](https://github.com/willnguyen1312/zoom-image/assets/17794897/254bd6f4-89ff-471a-ab74-9b857a840f4b)

Could you share with me the example you found that issue or CodeSandbox link will be great? Thank you :)

**Comment by hfall** [comment]
I'm testing on my chrome/safari:

[test.webm](https://github.com/willnguyen1312/zoom-image/assets/15349046/5a8755ba-7569-4dcb-bd11-d0554b0b01f5)

**Comment by willnguyen1312** [comment]
Sorry @hfall, I accidentally closed your issue. It should be fixed by now. Please check again on your end to see whether it's still available. Thanks again for your input 😉

**Comment by hfall** [comment]
Excellent! It works fine now. 🥇
